name: OSINT Tool CI

on: [push, pull_request]

jobs:
  quality:
    name: Code Quality Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pylint httpx aiosqlite beautifulsoup4 types-requests

    - name: Run MyPy (strict type checking)
      run: |
        # Check both src/ directory and root Python files
        if [ -d "src" ]; then
          mypy src/ --strict
        else
          echo "No src directory found, checking for Python files in root"
          find . -name "*.py" -exec mypy {} --strict \;
        fi

    - name: Run Pylint
      run: |
        if [ -d "src" ]; then
          pylint src/ --fail-under=9.0
        else
          pylint $(find . -name "*.py") --fail-under=9.0
        fi

    - name: Show Python files structure
      run: |
        echo "Current directory structure:"
        ls -la
        echo "Python files found:"
        find . -name "*.py" | head -10

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: quality
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -e .

    - name: Run basic functionality test
      run: |
        python -c "
        # Test basic imports
        import json
        import asyncio
        import httpx
        from typing import Dict, Any
        print('✅ All imports successful')
        
        # Test type annotations
        def test_func() -> Dict[str, Any]:
            return {'test': 'data'}
        result = test_func()
        print('✅ Type annotations working')
        "

  windows-quality:
    name: Windows Quality Check
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pylint httpx aiosqlite beautifulsoup4 types-requests

    - name: Run MyPy on Windows
      run: |
        if (Test-Path "src") {
          mypy src/ --strict
        } else {
          Get-ChildItem -Recurse -Filter "*.py" | ForEach-Object { mypy $_.FullName --strict }
        }

    - name: Run Pylint on Windows
      run: |
        if (Test-Path "src") {
          pylint src/ --fail-under=9.0
        } else {
          $pythonFiles = Get-ChildItem -Recurse -Filter "*.py" | Select-Object -ExpandProperty FullName
          if ($pythonFiles) {
            pylint $pythonFiles --fail-under=9.0
          }
        }
